### ISSUE TITLE
Apply button for favicon looks er not uit

### ISSUE THREAD

**Issue by JelCraft** [JelNet-webapplications/TabCustomiser#14]
<img width="171" alt="image" src="https://user-images.githubusercontent.com/61025393/215885504-5ae14bbc-8630-42d1-80f5-ffd6d8f2934a.png">
Dit moeten we ook eindelijk een keer fixen. Misschien een ronde knop met een vinkje aan de rechter kant binnen in het tekstvak?

Dan kunnen we hetzelfde doen met die terug naar orginele titel & favicon, maar dan pijltje teurg

**Comment by Vivaloz** [comment]
nu wel.
